[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lineage"
version = "0.1.0"
requires-python = "==3.10.19"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "scikit-learn",
    "seaborn",
    "hdbscan",
    "natsort",
    "absl-py",
    "jupyter",
    "loguru",
    "markdown",
]

[project.optional-dependencies]
linux = [
    "tensorflow[and-cuda]",
]
mac = [
    "tensorflow==2.18.0",
    "tensorflow-metal==1.2.0",
]

[tool.setuptools]
py-modules = []
